/********************************************************************
* Storage_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Storage_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableStorage_dict();
extern void G__cpp_setup_inheritanceStorage_dict();
extern void G__cpp_setup_typetableStorage_dict();
extern void G__cpp_setup_memvarStorage_dict();
extern void G__cpp_setup_globalStorage_dict();
extern void G__cpp_setup_memfuncStorage_dict();
extern void G__cpp_setup_funcStorage_dict();
extern void G__set_cpp_environmentStorage_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Storage.h"
#include "Storage.cxx"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Storage_dictLN_TClass;
extern G__linked_taginfo G__Storage_dictLN_TBuffer;
extern G__linked_taginfo G__Storage_dictLN_TMemberInspector;
extern G__linked_taginfo G__Storage_dictLN_TObject;
extern G__linked_taginfo G__Storage_dictLN_TBrowser;
extern G__linked_taginfo G__Storage_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Storage_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Storage_dictLN_TH1I;
extern G__linked_taginfo G__Storage_dictLN_Storage;

/* STUB derived class for protected member access */
